services:
  config-server:
    build: ./configserver
    ports:
      - "8079:8079"
    environment:
      - spring.cloud.config.server.git.default-label=master
    networks:
      - common
    restart: on-failure

  discovery-server:
    build: ./discoveryserver
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=devdocker
      - CONFIGURL=http://config-server:8079
    depends_on:
      - config-server
    networks:
      - common
    restart: on-failure

  gateway-server:
    build: ./gatewayserver
    ports:
      - "8001:8001"
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=devdocker
      - CONFIGURL=http://config-server:8079
    depends_on:
      - config-server
      - discovery-server
    networks:
      - common
    restart: on-failure

  auth-service:
    build:
      context: ./authservice
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8086:8086"
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=devdocker
      - CONFIGURL=http://config-server:8079
    depends_on:
      - postgres
      - discovery-server
      - config-server
    networks:
      - common
    restart: on-failure

  customer-service:
    build:
      context: ./customerservice
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8083:8083"
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=devdocker
      - CONFIGURL=http://config-server:8079
    depends_on:
      - postgres
      - discovery-server
      - config-server
    networks:
      - common
    restart: on-failure

  order-service:
    build:
      context: ./orderservice
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=devdocker
      - CONFIGURL=http://config-server:8079
    depends_on:
      - mongodb
      - discovery-server
      - config-server
    networks:
      - common
    restart: on-failure

  product-service:
    build:
      context: ./productservice
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8084:8084"
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=devdocker
      - CONFIGURL=http://config-server:8079
    depends_on:
      - postgres
      - discovery-server
      - config-server
    networks:
      - common
    restart: on-failure

  invoice-service:
    build:
      context: ./invoiceservice
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=devdocker
      - CONFIGURL=http://config-server:8079
    depends_on:
      - postgres
      - discovery-server
      - config-server
    networks:
      - common
    restart: on-failure

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-volume:/data/db
    networks:
      - common

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql-volume:/var/lib/postgresql/data
    networks:
      - common

volumes:
  postgresql-volume:
    name: postgresql-volume
  mongo-volume:
    name: mongo-volume

networks:
  common:
    driver: bridge